version: '3.8'

# This override file allows you to run specific services without rebuilding everything
# Usage: docker-compose up <service-name>

services:
  # Just import backend from main compose file
  backend: {}

  frontend:
    # Use a pre-built static frontend for faster testing
    image: nginx:alpine
    volumes:
      - ./frontend-static:/usr/share/nginx/html
      - ./frontend-static/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"

  llm:
    # Use official image for faster startup
    image: ollama/ollama:latest
    # Add the health check commands directly
    command: sh -c "apt-get update && apt-get install -y curl || true && ollama serve"